#!/bin/sh
# Copyright (c) 2015 Shawn Webb
# License: 2-clause BSD

if [ -z "${version}" ]; then
	version=""
fi

	if [ -z ${version} ]; then
		version=$(uname -v | awk '{print $1 " " $3;}')
		version=${version%\(*}
	fi
echo ${version}
#	cat<<EOF
#		{
#			"name": "kernel_version",
#			"full_text": "KVER: ${version}"
#		}
#EOF
